# Generated by Django 6.0.1 on 2026-01-18 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.property')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('HOLD', 'Hold'), ('RESERVED', 'Reserved'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='HOLD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_rooms', to='booking.room')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['check_in_date', 'check_out_date'], name='booking_boo_check_i_b839ca_idx'), models.Index(fields=['status', 'created_at'], name='booking_boo_status_0a3284_idx'), models.Index(fields=['room_id', 'check_in_date', 'check_out_date'], name='booking_boo_room_id_ad4bbf_idx'), models.Index(fields=['code'], name='booking_boo_code_816ff8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_in_date__lt', models.F('check_out_date'))), name='check_date_order')],
                'unique_together': {('room', 'check_in_date', 'check_out_date')},
            },
        ),
    ]
