# Generated by Django 6.0.1 on 2026-01-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, upload_to='property_photos'),
        ),
    ]
