# Generated by Django 6.0.1 on 2026-01-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_property_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_nights', models.PositiveSmallIntegerField(default=1)),
                ('max_nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('refundable', models.BooleanField(default=True)),
                ('cancellation_deadline_days', models.PositiveSmallIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='booking.room')),
            ],
            options={
                'verbose_name': 'Rate Plan',
                'verbose_name_plural': 'Rate Plans',
                'ordering': ['room__property__name', 'room__name', 'code'],
                'unique_together': {('room', 'code')},
            },
        ),
    ]
